site_name: ili2py Docs
docs_dir: mkdocs

nav:
  - Home: index.md
  - Installation: installation.md
  - Code:
      - Classes:
          - HasRef: HasRef.md # only as a mkdocstrings example for now

plugins:
  - search
  - autorefs
  - mkdocstrings:
        default_handler: python
        handlers:
          python:
            paths: [../../src]
            options:
              show_submodules: true
              show_if_no_docstring: true

theme:
  name: material


#markdown_extensions:
#  - admonition   # for snippets
#  - pymdownx.superfences   # for enhanced code blocks
#  - attr_list  # for usage of html and css in markdown
#  - pymdownx.emoji:  # for emojis
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg