site_name: ili2py Documentation
docs_dir: mkdocs
extra_css:
  - style.css
repo_name: rudert-geoinformatik/ili2py
repo_url: https://github.com/rudert-geoinformatik/ili2py
edit_uri: https://github.com/rudert-geoinformatik/ili2py/tree/master/docs/
nav:
  - "Home": index.md
  - "User Guide":
      - "Get started": user_guide/start.md
      - "Diagrams": user_guide/diagram.md
      - "Python Classes": user_guide/python_classes.md
      - "CLI Reference": user_guide/cli-reference.md
      - "CLI Binary usage": user_guide/cli-binary.md
  - "Feature Status":
      - "Overview": feature_status/index.md
      - "Reading IlisMeta16": feature_status/ilismeta16.md
      - "Index Mapper":  feature_status/index_mapper.md
      - "Python Classes":  feature_status/python_classes.md
      - "Diagrams":  feature_status/diagrams.md
      - "Open Questions": feature_status/questions.md
  - "Documents":
      - "Overview": documents/overview.md
      - "Report (Nov '23)": documents/report/report.md
  - "DEV Guide":
      - "Python Classes usage": dev_guide/python_classes.md
  - Code:
      - Interfaces:
          - "INTERLIS 2.4":
              - "IlisMeta16": code/ilismeta16.md

plugins:
  - search
  - autorefs
  - mermaid2
  - glightbox:
      auto_caption: true       # Untertitel automatisch aus dem Bildtitel
      touchNavigation: true
      loop: true
      effect: zoom
  - mkdocstrings:
        default_handler: python
        handlers:
          python:
            paths:
              - "../../src"
            options:
              show_submodules: true
              show_if_no_docstring: true

theme:
  name: material
  logo: assets/img/logo.1.svg
  favicon: assets/img/logo.1.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


markdown_extensions:
  - admonition   # for snippets
  - mkdocs-click
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
