site_name: ili2py Docs
docs_dir: mkdocs
extra_css:
  - style.css
nav:
  - Welcome: index.md
  - "Quick Start": quick_start.md
  - "DEV Setup": dev_setup.md
  - "Feature Status":
      - "Overview": feature_status/index.md
      - "Reading IlisMeta16": feature_status/ilismeta16.md
      - "Index Mapper":  feature_status/index_mapper.md
      - "Python Classes":  feature_status/python_classes.md
      - "UML Diagrams":  feature_status/uml_diagrams.md

  - Installation: installation.md
  - Usage:
      - UML: uml.md
  - Code:
      - Interfaces:
          - "INTERLIS 2.4":
              - "IlisMeta16": code/ilismeta16.md

plugins:
  - search
  - autorefs
  - mermaid2
  - mkdocstrings:
        default_handler: python
        handlers:
          python:
            paths:
              - "../../src"
            options:
              show_submodules: true
              show_if_no_docstring: true

theme:
  name: material


markdown_extensions:
  - admonition   # for snippets
#  - pymdownx.superfences   # for enhanced code blocks
#  - attr_list  # for usage of html and css in markdown
#  - pymdownx.emoji:  # for emojis
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg
