name: Build Binaries

on:
  push:
    branches:
      - "*github-build-edit"
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies (Linux/MacOS)
        if: runner.os != 'Windows'
        run: |
          make install-dev

      - name: Build binary (Linux/MacOS)
        if: runner.os != 'Windows'
        run: |
          make binary

      - name: Test binary (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          # check if it exits non zero
          ./dist/ili2py --version
          if [ $? -ne 0 ]; then
            echo "Binary test failed"
            exit 1
          fi
          ./dist/ili2py -v diagram -i tests/data/models/OeREBKRMtrsfr_V2_0/OeREBKRMtrsfr_V2_0.imd -f plantuml -o .generated
          ./dist/ili2py -v diagram -i tests/data/models/OeREBKRMtrsfr_V2_0/OeREBKRMtrsfr_V2_0.imd -f mermaid -o .generated
          ./dist/ili2py -v python-classes -i tests/data/models/OeREBKRMtrsfr_V2_0/OeREBKRMtrsfr_V2_0.imd -o .generated -l interface

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          python -m venv .venv
          .venv\Scripts\python.exe -m pip install --upgrade pip wheel setuptools
          .venv\Scripts\pip.exe install -e .[dev]

      - name: Build binary (Windows)
        if: runner.os == 'Windows'
        run: |
          .venv\Scripts\pyinstaller --name ili2py --onefile --noconfirm --add-data "src\ili2py:ili2py" src\ili2py\cli.py

      - name: Test binary (Windows)
        if: runner.os == 'Windows'
        run: |
          # check if it exits non zero
          $binary = ".\dist\ili2py.exe"
          # check exit code
          & $binary --version
          if ($LASTEXITCODE -ne 0) { exit 1 }
          .\dist\ili2py.exe -v diagram -i tests\data\models\OeREBKRMtrsfr_V2_0\OeREBKRMtrsfr_V2_0.imd -f plantuml -o .generated
          .\dist\ili2py.exe -v diagram -i tests\data\models\OeREBKRMtrsfr_V2_0\OeREBKRMtrsfr_V2_0.imd -f mermaid -o .generated
          .\dist\ili2py.exe -v python-classes -i tests\data\models\OeREBKRMtrsfr_V2_0\OeREBKRMtrsfr_V2_0.imd -o .generated -l interface

      - name: Rename binary
        run: |
          mkdir dist_upload
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            mv dist/ili2py dist_upload/ili2py-linux-latest
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/ili2py dist_upload/ili2py-macos-latest
          else
            mv dist/ili2py.exe dist_upload/ili2py-windows-latest.exe
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-binary
          path: dist_upload/*
          retention-days: 3
  release_latest:
    name: Release Latest
    permissions:
      contents: write
    needs: [ build ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist_upload

      - name: Flatten artifacts for release
        run: |
          mkdir dist_flat
          find dist_upload -type f -exec cp {} dist_flat/ \;

      - name: Create GitHub Release Latest
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: dist_flat/*
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
